# Generated by Django 6.0 on 2026-02-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_blogs_travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='categories',
        ),
    ]
