# Generated by Django 6.0 on 2026-03-02 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_blogs_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.traveldiary'),
        ),
    ]
