# Generated by Django 6.0 on 2026-01-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_plan_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('descriptions', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='plan_trip',
            name='categories',
            field=models.ManyToManyField(blank=True, to='dashboard.categories'),
        ),
        migrations.AddField(
            model_name='traveldiary',
            name='categories',
            field=models.ManyToManyField(blank=True, to='dashboard.categories'),
        ),
    ]
