# Generated by Django 6.0 on 2026-01-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_categories_plan_trip_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='descriptions',
            field=models.TextField(),
        ),
    ]
