# Generated by Django 6.0 on 2026-01-19 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_categories_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_trip',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='traveldiary',
            name='categories',
        ),
        migrations.AddField(
            model_name='plan_trip',
            name='categories',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveldiary',
            name='categories',
            field=models.ForeignKey(blank=True, default=1.01, on_delete=django.db.models.deletion.CASCADE, to='dashboard.categories'),
            preserve_default=False,
        ),
    ]
