# Generated by Django 6.0 on 2026-01-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='about',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
