# Generated by Django 6.0 on 2026-01-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_cutomize_categories_gallary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cutomize_categories',
        ),
    ]
